apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: envoy-gateway
spec:
  interval: 60m
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    tag: 1.5.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: envoy-gateway

